/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Map;

public class CustomHashMap implements Map<K,V>{

}

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
